//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P_UX_ACD_EgalAhmeOmar.Ressources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Deutsh {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Deutsh() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("P_UX_ACD_EgalAhmeOmar.Ressources.Deutsh", typeof(Deutsh).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ticket Aéroport.
        /// </summary>
        internal static string _nameAirporticket {
            get {
                return ResourceManager.GetString("_nameAirporticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ticket Dineyland Paris.
        /// </summary>
        internal static string _nameChessyDisneyticket {
            get {
                return ResourceManager.GetString("_nameChessyDisneyticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ticket Paris Visite.
        /// </summary>
        internal static string _nameParisVisiteticket {
            get {
                return ResourceManager.GetString("_nameParisVisiteticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ticket à prix Réduit.
        /// </summary>
        internal static string _nameReducedticket {
            get {
                return ResourceManager.GetString("_nameReducedticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ticket standard.
        /// </summary>
        internal static string _nameStandardticket {
            get {
                return ResourceManager.GetString("_nameStandardticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aéroport.
        /// </summary>
        internal static string btnAirportticket {
            get {
                return ResourceManager.GetString("btnAirportticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retour.
        /// </summary>
        internal static string btnBack {
            get {
                return ResourceManager.GetString("btnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retour.
        /// </summary>
        internal static string btnBackinHeader {
            get {
                return ResourceManager.GetString("btnBackinHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tickets Normaux.
        /// </summary>
        internal static string btnBasicTickets {
            get {
                return ResourceManager.GetString("btnBasicTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disneyland Paris.
        /// </summary>
        internal static string btnChessydisneyTicket {
            get {
                return ResourceManager.GetString("btnChessydisneyTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deutsh.
        /// </summary>
        internal static string btnDeutshinFirstpage {
            get {
                return ResourceManager.GetString("btnDeutshinFirstpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deutsh.
        /// </summary>
        internal static string btnDeutshinFooter {
            get {
                return ResourceManager.GetString("btnDeutshinFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous n&apos;avez de Carte Navigo, Appuyer ici.
        /// </summary>
        internal static string btnDonthaveNavigo {
            get {
                return ResourceManager.GetString("btnDonthaveNavigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Moins.
        /// </summary>
        internal static string btnDownreducedPrice {
            get {
                return ResourceManager.GetString("btnDownreducedPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Moins.
        /// </summary>
        internal static string btnDownstandardPrice {
            get {
                return ResourceManager.GetString("btnDownstandardPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à English.
        /// </summary>
        internal static string btnEnglishinFirstpage {
            get {
                return ResourceManager.GetString("btnEnglishinFirstpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à English.
        /// </summary>
        internal static string btnEnglishinFooter {
            get {
                return ResourceManager.GetString("btnEnglishinFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Français.
        /// </summary>
        internal static string btnFrenchinFooter {
            get {
                return ResourceManager.GetString("btnFrenchinFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Italino.
        /// </summary>
        internal static string btnItalianinFirstpage {
            get {
                return ResourceManager.GetString("btnItalianinFirstpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Italino.
        /// </summary>
        internal static string btnItalianinFooter {
            get {
                return ResourceManager.GetString("btnItalianinFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prochain Achat.
        /// </summary>
        internal static string btnNextpurchase {
            get {
                return ResourceManager.GetString("btnNextpurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Non.
        /// </summary>
        internal static string btnNoforReceipt {
            get {
                return ResourceManager.GetString("btnNoforReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paris Visite.
        /// </summary>
        internal static string btnParisvisite {
            get {
                return ResourceManager.GetString("btnParisvisite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Passer, Vous êtes déjâ en français.
        /// </summary>
        internal static string btnPasstoFrench {
            get {
                return ResourceManager.GetString("btnPasstoFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Payer.
        /// </summary>
        internal static string btnPay {
            get {
                return ResourceManager.GetString("btnPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Déposer votre carte Navigo.
        /// </summary>
        internal static string btnPlacenavigoPass {
            get {
                return ResourceManager.GetString("btnPlacenavigoPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Español.
        /// </summary>
        internal static string btnSpanishinFirstpage {
            get {
                return ResourceManager.GetString("btnSpanishinFirstpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Español.
        /// </summary>
        internal static string btnSpanishinFooter {
            get {
                return ResourceManager.GetString("btnSpanishinFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tickets Spéciaux.
        /// </summary>
        internal static string btnSpecialtickets {
            get {
                return ResourceManager.GetString("btnSpecialtickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stop.
        /// </summary>
        internal static string btnStopInFooter {
            get {
                return ResourceManager.GetString("btnStopInFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Plus.
        /// </summary>
        internal static string btnUpreducedPrice {
            get {
                return ResourceManager.GetString("btnUpreducedPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Plus.
        /// </summary>
        internal static string btnUpstandardPrice {
            get {
                return ResourceManager.GetString("btnUpstandardPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Valider.
        /// </summary>
        internal static string btnValidatorcard {
            get {
                return ResourceManager.GetString("btnValidatorcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Valider.
        /// </summary>
        internal static string btnValidatorcoinsAndnotes {
            get {
                return ResourceManager.GetString("btnValidatorcoinsAndnotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Valider.
        /// </summary>
        internal static string btnValidatorgooglePay {
            get {
                return ResourceManager.GetString("btnValidatorgooglePay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Valider.
        /// </summary>
        internal static string btnValidatorInfos {
            get {
                return ResourceManager.GetString("btnValidatorInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Oui.
        /// </summary>
        internal static string btnYesforReceipt {
            get {
                return ResourceManager.GetString("btnYesforReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cartes banquaires acceptées :.
        /// </summary>
        internal static string lblAcceptedbankCards {
            get {
                return ResourceManager.GetString("lblAcceptedbankCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pièces et billets acceptés :.
        /// </summary>
        internal static string lblAcceptedcoinsAndnotes {
            get {
                return ResourceManager.GetString("lblAcceptedcoinsAndnotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deutsh.
        /// </summary>
        internal static string lblDeutshlangage {
            get {
                return ResourceManager.GetString("lblDeutshlangage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à English.
        /// </summary>
        internal static string lblEnglishLangage {
            get {
                return ResourceManager.GetString("lblEnglishLangage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Italino.
        /// </summary>
        internal static string lblItalianlangage {
            get {
                return ResourceManager.GetString("lblItalianlangage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 0.
        /// </summary>
        internal static string lblNumberreducedTickets {
            get {
                return ResourceManager.GetString("lblNumberreducedTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nombre de billet Spéciaux :.
        /// </summary>
        internal static string lblnumberSpecialTicket {
            get {
                return ResourceManager.GetString("lblnumberSpecialTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 0.
        /// </summary>
        internal static string lblNumberstandardTickets {
            get {
                return ResourceManager.GetString("lblNumberstandardTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type de tarification :.
        /// </summary>
        internal static string lblRadiobuttonTypeticket {
            get {
                return ResourceManager.GetString("lblRadiobuttonTypeticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prix réduit :.
        /// </summary>
        internal static string lblReducedprice {
            get {
                return ResourceManager.GetString("lblReducedprice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Selectionnner une langue.
        /// </summary>
        internal static string lblSelectlangages {
            get {
                return ResourceManager.GetString("lblSelectlangages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Español.
        /// </summary>
        internal static string lblSpanishlangage {
            get {
                return ResourceManager.GetString("lblSpanishlangage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prix standard :.
        /// </summary>
        internal static string lblStandardprice {
            get {
                return ResourceManager.GetString("lblStandardprice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Faites un choix :.
        /// </summary>
        internal static string lbltextinHeader {
            get {
                return ResourceManager.GetString("lbltextinHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mes choix :.
        /// </summary>
        internal static string lbltextinHeaderinAllmyChoices {
            get {
                return ResourceManager.GetString("lbltextinHeaderinAllmyChoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voulez-vous une quittance ?.
        /// </summary>
        internal static string lbltextinHeaderinBillorNot {
            get {
                return ResourceManager.GetString("lbltextinHeaderinBillorNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total à payer :.
        /// </summary>
        internal static string lbltextinHeaderinSelectpaymentMethod {
            get {
                return ResourceManager.GetString("lbltextinHeaderinSelectpaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à total en cours :.
        /// </summary>
        internal static string lblTextInside {
            get {
                return ResourceManager.GetString("lblTextInside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Utiliser Google Pay :.
        /// </summary>
        internal static string lblTypeofPayement {
            get {
                return ResourceManager.GetString("lblTypeofPayement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 5 Jours.
        /// </summary>
        internal static string radioBtnfiveSpecialticket {
            get {
                return ResourceManager.GetString("radioBtnfiveSpecialticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1 Jour.
        /// </summary>
        internal static string radioBtnoneSpecialticket {
            get {
                return ResourceManager.GetString("radioBtnoneSpecialticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prix réduit.
        /// </summary>
        internal static string radioBtnreducedPrice {
            get {
                return ResourceManager.GetString("radioBtnreducedPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prix standard.
        /// </summary>
        internal static string radioBtnStandardprice {
            get {
                return ResourceManager.GetString("radioBtnStandardprice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 3 Jours.
        /// </summary>
        internal static string radioBtnthreeSpecialticket {
            get {
                return ResourceManager.GetString("radioBtnthreeSpecialticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vos billet ont bien été ajoutée au panier..
        /// </summary>
        internal static string validTicketselected {
            get {
                return ResourceManager.GetString("validTicketselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucun ticket n&apos;est selectionné !.
        /// </summary>
        internal static string zeroTicketselected {
            get {
                return ResourceManager.GetString("zeroTicketselected", resourceCulture);
            }
        }
    }
}
